root: true
env:
  node: true
  es6: true
parser: babel-eslint
plugins:
  - babel
rules:
  indent:
    - 2
    - 4
  semi:
    - 2
    - never
    - beforeStatementContinuationChars: always
  quotes:
    - 2
    - single
  no-var:
    - 2
